# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_Rzb3zcYQlHU8HiyJysT56sJOV2T1YP3
"""

import streamlit as st
import tensorflow as tf
import numpy as np
from PIL import Image

model = tf.keras.models.load_model("brain_tumor_mobilenetv2.h5")
class_names = ['glioma', 'meningioma', 'no_tumor', 'pituitary']

st.title("🧠 Brain Tumor Classifier")

file = st.file_uploader("Upload an MRI Image", type=["jpg", "jpeg", "png"])
if file:
    image = Image.open(file).convert("RGB")
    st.image(image, caption="Uploaded Image", use_column_width=True)

    img = image.resize((224, 224))
    img_array = np.expand_dims(np.array(img)/255.0, axis=0)
    pred = model.predict(img_array)
    pred_class = class_names[np.argmax(pred)]

    st.markdown(f"### Prediction: `{pred_class}`")
    st.markdown(f"Confidence: `{np.max(pred)*100:.2f}%`")

